name: Rector

on:
  pull_request:

jobs:
  rector:
    runs-on: ubuntu-latest
    steps:
      - if: github.event.pull_request.head.repo.full_name == github.repository
        name: Checkout code
        uses: actions/checkout@v2.4.0
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.event.pull_request.head.ref }}

      - if: github.event.pull_request.head.repo.full_name != github.repository
        name: Checkout code
        uses: actions/checkout@v2.4.0

      - name: Setup PHP
        uses: shivammathur/setup-php@2.16.0

      - name: Install dependencies
        uses: ramsey/composer-install@v1

      - run: vendor/bin/rector process --ansi

      - run: vendor/bin/ecs check --fix --ansi

      - if: github.event.pull_request.head.repo.full_name == github.repository
        uses: EndBug/add-and-commit@v8
        with:
          add: .
          message: "Rector Rectify"
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
